### ISSUE TITLE
Lag issue on commands

### ISSUE THREAD

**Issue by Zoiter7** [garagepoort/StaffPlusPlus#111]
MC Versión: 1.16.3
Using latest Staff++ versión

Hello, there is a issue when you run some commands.

• For example when you run /freeze <player> server is start to lagging for some seconds, the same with command /teleport
Crash log: https://pastebin.com/fDLz4aBW

• Also other small bug if you use /freeze command without args returns error.
`[19:51:02] [Server thread/INFO]: Zoiter7 issued server command: /freeze
[19:51:02] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'freeze' in net.shortninja.staffplus.server.command.cmd.mode.FreezeCmd(freeze)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.16.3.jar:git-Paper-220]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1908) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1719) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-220]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-220]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at net.shortninja.staffplus.server.command.cmd.mode.FreezeCmd.getMinimumArguments(FreezeCmd.java:59) ~[?:?]
	at net.shortninja.staffplus.server.command.cmd.StaffPlusPlusCmd.lambda$execute$0(StaffPlusPlusCmd.java:43) ~[?:?]
	at net.shortninja.staffplus.common.CommandUtil.executeCommand(CommandUtil.java:14) ~[?:?]
	at net.shortninja.staffplus.server.command.cmd.StaffPlusPlusCmd.execute(StaffPlusPlusCmd.java:39) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.3.jar:git-Paper-220]
	... 17 more`

• And other suggestion, add possibility to turn off the "StaffChat over bungeecord" feature.

**Comment by garagepoort** [comment]
Hi Zoiter,
Are you using the latest version of Staff++?

**Comment by garagepoort** [comment]
@Zoiter7 can you try with the latest version to see if the problems persist?

**Comment by Zoiter7** [comment]
Hello, sorry for delay, it works well now.

Thanks :)

**Comment by garagepoort** [comment]
Closing because the lagging issues are solved. 
Option for enabling/disabling bungeecord staffchat 
Version 1.16.27

**Comment by garagepoort** [comment]
Closing because the lagging issues are solved.
Option for enabling/disabling bungeecord staffchat
Version 1.16.27
