### ISSUE TITLE
Error on saving file

### ISSUE THREAD

**Issue by Zoiter7** [garagepoort/StaffPlusPlus#122]
Version: Spigot 1.16.3
StaffPlus version: Latest for 1.16.3

1. When user disconnects from server the user keeps his inv.
2. **Sometimes when user disconnect from server console throws this error with saving data.**

`[07:30:59] [Craft Scheduler Thread - 1014/WARN]: [StaffPlus] Plugin StaffPlus v1.16.32 generated an exception while executing task 7731272
java.lang.NullPointerException: Nodes must be provided.
	at org.yaml.snakeyaml.nodes.NodeTuple.<init>(NodeTuple.java:28) ~[patched_1.16.3.jar:git-Paper-251]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:164) ~[patched_1.16.3.jar:git-Paper-251]
	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:321) ~[patched_1.16.3.jar:git-Paper-251]
	at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:24) ~[patched_1.16.3.jar:git-Paper-251]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[patched_1.16.3.jar:git-Paper-251]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157) ~[patched_1.16.3.jar:git-Paper-251]
	at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:321) ~[patched_1.16.3.jar:git-Paper-251]
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[patched_1.16.3.jar:git-Paper-251]
	at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:65) ~[patched_1.16.3.jar:git-Paper-251]
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:275) ~[patched_1.16.3.jar:git-Paper-251]
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:243) ~[patched_1.16.3.jar:git-Paper-251]
	at org.yaml.snakeyaml.Yaml.dump(Yaml.java:220) ~[patched_1.16.3.jar:git-Paper-251]
	at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:41) ~[patched_1.16.3.jar:git-Paper-251]
	at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:65) ~[patched_1.16.3.jar:git-Paper-251]
	at net.shortninja.staffplus.server.data.file.DataFile.save(DataFile.java:45) ~[?:?]
	at net.shortninja.staffplus.session.SessionLoader.lambda$saveSession$0(SessionLoader.java:81) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-251]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.3.jar:git-Paper-251]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.3.jar:git-Paper-251]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`

**Comment by garagepoort** [comment]
Hi @Zoiter7,

Could you go into a bit more detail about the first point?

**Comment by garagepoort** [comment]
inactivity
