### ISSUE TITLE
[bug] exception related to luckperms api, context calculation

### ISSUE THREAD

**Issue by heathfx** [garagepoort/StaffPlusPlus#135]
### The problem
When a new player, never seen before joins my server. I'm seeing this in the logs:

I also have steps to reproduce down below.

`[20:19:13 INFO]: UUID of player HarmWasTaken is 81b521bf-ec53-46a5-a64c-bec0d9cee0d0
[20:19:13 WARN]: [LuckPerms] An exception was thrown by net.shortninja.staffplus.staff.mode.StaffModeLuckPermsContextCalculator whilst calculating the context of subject CraftPlayer{name=HarmWasTaken}
[20:19:13 WARN]: java.lang.RuntimeException: Trying to instantiate session for offline user
[20:19:13 WARN]:        at net.shortninja.staffplus.session.SessionLoader.buildNewSession(SessionLoader.java:45)
[20:19:13 WARN]:        at net.shortninja.staffplus.session.SessionLoader.loadSession(SessionLoader.java:39)
[20:19:13 WARN]:        at net.shortninja.staffplus.session.SessionManager.get(SessionManager.java:31)
[20:19:13 WARN]:        at net.shortninja.staffplus.staff.mode.StaffModeLuckPermsContextCalculator.calculate(StaffModeLuckPermsContextCalculator.java:19)
[20:19:13 WARN]:        at net.shortninja.staffplus.staff.mode.StaffModeLuckPermsContextCalculator.calculate(StaffModeLuckPermsContextCalculator.java:9)
[20:19:13 WARN]:        at me.lucko.luckperms.common.context.ContextManager.calculate(ContextManager.java:138)
[20:19:13 WARN]:        at me.lucko.luckperms.common.context.QueryOptionsCache.supply(QueryOptionsCache.java:54)
[20:19:13 WARN]:        at me.lucko.luckperms.common.context.QueryOptionsCache.supply(QueryOptionsCache.java:42)
[20:19:13 WARN]:        at me.lucko.luckperms.common.cache.ExpiringCache.get(ExpiringCache.java:64)
[20:19:13 WARN]:        at me.lucko.luckperms.common.context.QueryOptionsCache.getQueryOptions(QueryOptionsCache.java:59)
[20:19:13 WARN]:        at me.lucko.luckperms.bukkit.inject.permissible.LuckPermsPermissible.hasPermission(LuckPermsPermissible.java:175)
[20:19:13 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:206)
[20:19:13 WARN]:        at me.egg82.antivpn.events.PlayerLoginUpdateNotifyHandler.accept(PlayerLoginUpdateNotifyHandler.java:31)
[20:19:13 WARN]:        at me.egg82.antivpn.AntiVPN.lambda$loadEvents$9(AntiVPN.java:360)
[20:19:13 WARN]:        at me.egg82.antivpn.external.ninja.egg82.events.SingleEventSubscriber.call(SingleEventSubscriber.java:101)
[20:19:13 WARN]:        at me.egg82.antivpn.external.ninja.egg82.events.BukkitEventSubscriber.call(BukkitEventSubscriber.java:50)
[20:19:13 WARN]:        at me.egg82.antivpn.external.ninja.egg82.events.BukkitEventSubscriber.lambda$new$0(BukkitEventSubscriber.java:31)
[20:19:13 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[20:19:13 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:19:13 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[20:19:13 WARN]:        at net.minecraft.server.v1_16_R3.PlayerList.attemptLogin(PlayerList.java:677)
[20:19:13 WARN]:        at net.minecraft.server.v1_16_R3.LoginListener.c(LoginListener.java:148)
[20:19:13 WARN]:        at net.minecraft.server.v1_16_R3.LoginListener.tick(LoginListener.java:66)
[20:19:13 WARN]:        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:564)
[20:19:13 WARN]:        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:150)
[20:19:13 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1443)
[20:19:13 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378)
[20:19:13 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1268)
[20:19:13 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000)
[20:19:13 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174)
[20:19:13 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)
[20:19:13 WARN]: [LuckPerms] An exception was thrown by net.shortninja.staffplus.staff.mode.StaffModeLuckPermsContextCalculator whilst calculating the context of subject CraftPlayer{name=HarmWasTaken}
[20:19:13 WARN]: java.lang.RuntimeException: Trying to instantiate session for offline user
[20:19:13 WARN]:        at net.shortninja.staffplus.session.SessionLoader.buildNewSession(SessionLoader.java:45)
[20:19:13 WARN]:        at net.shortninja.staffplus.session.SessionLoader.loadSession(SessionLoader.java:39)
[20:19:13 WARN]:        at net.shortninja.staffplus.session.SessionManager.get(SessionManager.java:31)
[20:19:13 WARN]:        at net.shortninja.staffplus.staff.mode.StaffModeLuckPermsContextCalculator.calculate(StaffModeLuckPermsContextCalculator.java:19)
[20:19:13 WARN]:        at net.shortninja.staffplus.staff.mode.StaffModeLuckPermsContextCalculator.calculate(StaffModeLuckPermsContextCalculator.java:9)
[20:19:13 WARN]:        at me.lucko.luckperms.common.context.ContextManager.calculate(ContextManager.java:138)
[20:19:13 WARN]:        at me.lucko.luckperms.common.context.QueryOptionsCache.supply(QueryOptionsCache.java:54)
[20:19:13 WARN]:        at me.lucko.luckperms.common.context.QueryOptionsCache.supply(QueryOptionsCache.java:42)
[20:19:13 WARN]:        at me.lucko.luckperms.common.cache.ExpiringCache.get(ExpiringCache.java:64)
[20:19:13 WARN]:        at me.lucko.luckperms.common.context.QueryOptionsCache.getQueryOptions(QueryOptionsCache.java:59)
[20:19:13 WARN]:        at me.lucko.luckperms.bukkit.inject.permissible.LuckPermsPermissible.hasPermission(LuckPermsPermissible.java:175)
[20:19:13 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:206)
[20:19:13 WARN]:        at net.minecraft.server.v1_16_R3.CommandListenerWrapper.hasPermission(CommandListenerWrapper.java:167)
[20:19:13 WARN]:        at net.minecraft.server.v1_16_R3.CommandListenerWrapper.hasPermission(CommandListenerWrapper.java:156)
[20:19:13 WARN]:        at net.minecraft.server.v1_16_R3.CommandAdvancement.a(SourceFile:36)
[20:19:13 WARN]:        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:79)
[20:19:13 WARN]:        at net.minecraft.server.v1_16_R3.CommandDispatcher.a(CommandDispatcher.java:303)
[20:19:13 WARN]:        at net.minecraft.server.v1_16_R3.CommandDispatcher.sendAsync(CommandDispatcher.java:261)
[20:19:13 WARN]:        at net.minecraft.server.v1_16_R3.CommandDispatcher.lambda$a$4(CommandDispatcher.java:250)
[20:19:13 WARN]:        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1429)
[20:19:13 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[20:19:13 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[20:19:13 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[20:19:13 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[20:19:13 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[20:19:13 WARN]: [StaffPlus] Player is has no modedata stored. Cannot remove mode.`

### Steps to reproduce
1. configure a 1.16.5 minecraft server
2. install LuckPerms-Bukkit-5.2.76.jar and staffplusplus-core-1.16.44.jar (the default configs are used)
3. launch the server and run "/whitelist off"
4. join the server
5. observe a similar exception to the one shown above in the server console

### Notes
- This happens only upon first join. subsequent joins do not throw this error.
- In the absense of LuckPerms, this error does not happen.
- Was also tested on LuckPerms-Bukkit-5.1.93.jar and staffplusplus-core-1.17.0.jar (compiled from latest master) and produced the same error
- You can cause this error to occur again by killing the server, deleting plugins/StaffPlus/data.yml and restarting the server.

**Comment by garagepoort** [comment]
Hi Infectus,

Thanks for the detailed bug report. I can reproduce it and it will be fixed with next release.

Garagepoort

**Comment by garagepoort** [comment]
Fixed in release 1.16.45
