### ISSUE TITLE
bug: server config files randomly update & reset properties?!

### ISSUE THREAD

**Issue by TGTGamer** [garagepoort/StaffPlusPlus#150]
I've attached both the file from my local config and the server-generated config. (with database redacted of cause)

[StaffPlus.zip](https://github.com/garagepoort/StaffPlusPlus/files/6122161/StaffPlus.zip)

I have 0 clues why it seems to be resetting my entire config. Would love to figure it out xD

**Comment by garagepoort** [comment]
In your config file I see the following:

```
  reporter-notifications:
      # The reporter will be notified the moment he comes online that he has reports OPEN or IN_PROGRESS
      notify-on-join: true
      # Enable status change notifications. Whenever a staff member changes the status to one of the specified statuses, the reporter will be notified (if he is online).
      # Statuses must be semi-colon separated
      status-change-notifications: IN_PROGRESS;RESOLVED;REJECTED
    report-types:
      - name: GRIEFED
        info: Select when you want to report someone destroying your property.
        material: MUSIC_DISC_11
      - name: BULLIED
        info: Something about bullying
        material: MUSIC_DISC_13
      - name: BUG
        info: Select this report type if you found a bug somewhere on the server
        material: MUSIC_DISC_BLOCKS
        ```
        
      The indentation of report types is wrong. Which causes the yaml parsing to fail.
      The code kind of crashes on this with the following exception:
      
      ```
      org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'string', line 73, column 3:
      enabled: true
      ^
expected <block end>, but found '<block mapping start>'
 in 'string', line 95, column 5:
        report-types:
        ^

        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:188) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:157) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:133) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        at net.shortninja.staffplus.server.data.config.AutoUpdater.updateConfig(AutoUpdater.java:26) ~[?:?]
        at net.shortninja.staffplus.StaffPlus.onEnable(StaffPlus.java:105) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:493) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:407) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:218) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'string', line 73, column 3:
      enabled: true
      ^
expected <block end>, but found '<block mapping start>'
 in 'string', line 95, column 5:
        report-types:
        ^

        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:235) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:95) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:119) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:150) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:416) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[spigot-1.16.5.jar:git-Spigot-cd23533-a82b212]
        ... 17 more

```

Fixing the indentation makes the updater work as expected.
```
# No permission required for regular users, requires 'permissions.report' permission for moderator commands.
reports-module:
  # Whether or not the plugin will use '/report' features.
  enabled: true

  # The sound that is played to staff when someone is reported.
  # Set to 'NONE' to disable.
  sound: ORB_PICKUP

  # The cooldown, in seconds, for using '/report'.
  # This is disabled for players with the 'permissions.report' permission.
  cooldown: 10

  # Whether or not the player that reported another player will be visible in GUIs.
  show-reporter: true

  # Whether or not a staff member must provide a reason when resolving/rejecting a report
  closing-reason-enabled: true

  reporter-notifications:
      # The reporter will be notified the moment he comes online that he has reports OPEN or IN_PROGRESS
      notify-on-join: true
      # Enable status change notifications. Whenever a staff member changes the status to one of the specified statuses, the reporter will be notified (if he is online).
      # Statuses must be semi-colon separated
      status-change-notifications: IN_PROGRESS;RESOLVED;REJECTED
  report-types:
    - name: GRIEFED
      info: Select when you want to report someone destroying your property.
      material: MUSIC_DISC_11
    - name: BULLIED
      info: Something about bullying
      material: MUSIC_DISC_13
    - name: BUG
      info: Select this report type if you found a bug somewhere on the server
      material: MUSIC_DISC_BLOCKS
````

I'll refactor the Update to be more robust.
Because currently it just starts behaving weird when there is a yaml parsing failure.

**Comment by TGTGamer** [comment]
fixed by fixing the indentation. I would love to see it through an error in console when this happens, cause I didn't even realise it was having any issues

**Comment by garagepoort** [comment]
I agree and it definitely shouldn't reset the config. I'll fix this with the next release

**Comment by garagepoort** [comment]
Fixed with latest release. Plugin will now fail to stat when there is a yaml parsing error.
