### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by MEOW2006** [garagepoort/StaffPlusPlus#151]
I have a problem with the plugin
it sends this in the console when I want to reload it 

```
[18:54:59 ERROR]: Error occurred while enabling StaffPlusPlusDiscord v1.16.12 (Is it up to date?)
java.lang.IllegalStateException: Method has too many Body parameters: public abstract void be.garagepoort.staffplusplus.discord.api.DiscordClient.sendFileEvent(java.lang.String,feign.form.FormData)
        at feign.Util.checkState(Util.java:130) ~[?:?]
        at feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:117) ~[?:?]
        at feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:66) ~[?:?]
        at feign.ReflectiveFeign$ParseHandlersByName.apply(ReflectiveFeign.java:154) ~[?:?]
        at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:52) ~[?:?]
        at feign.Feign$Builder.target(Feign.java:251) ~[?:?]
        at feign.Feign$Builder.target(Feign.java:247) ~[?:?]
        at be.garagepoort.staffplusplus.discord.reports.ReportListener.init(ReportListener.java:44) ~[?:?]
        at be.garagepoort.staffplusplus.discord.StaffPlusPlusDiscord.initListener(StaffPlusPlusDiscord.java:66) ~[?:?]
        at be.garagepoort.staffplusplus.discord.StaffPlusPlusDiscord.initializeListeners(StaffPlusPlusDiscord.java:48) ~[?:?]
        at be.garagepoort.staffplusplus.discord.StaffPlusPlusDiscord.onEnable(StaffPlusPlusDiscord.java:36) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:git-Paper-545]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[server.jar:git-Paper-545]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[server.jar:git-Paper-545]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:304) ~[?:?]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:262) ~[?:?]
        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:391) ~[?:?]
        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) ~[?:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:git-Paper-545]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[server.jar:git-Paper-545]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[server.jar:git-Paper-545]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:772) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:413) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:380) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1216) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[server.jar:git-Paper-545]
        at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3108/0x00000000edc7aee0.run(Unknown Source) ~[?:?]
```
        
        -------------------------

        **IT'S UP TO DATE!**

**Comment by garagepoort** [comment]
The reason the above failed is probably because of the plugman reload. The discord plugin does not support being reloaded by plugman.
Discussed the real issue on discord with @MEOW2006. It was a configuration issue and is fixed.
