### ISSUE TITLE
Error after using /staff

### ISSUE THREAD

**Issue by KayleePhoto** [garagepoort/StaffPlusPlus#154]
I don't have much info here.
When ever I execute /staff in-game, console reads out this warning.
I didn't have an issue on v1.16.50
```
20.03 12:49:23 [Server] WARN Plugin StaffPlus v1.16.52 generated an exception while executing task 30784
20.03 12:49:23 [Server] INFO java.lang.NullPointerException: Nodes must be provided.
20.03 12:49:23 [Server] INFO at org.yaml.snakeyaml.nodes.NodeTuple.<init>(NodeTuple.java:28) ~[patched_1.16.4.jar:git-Paper-352]
20.03 12:49:23 [Server] INFO at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:164) ~[patched_1.16.4.jar:git-Paper-352]
20.03 12:49:23 [Server] INFO at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:321) ~[patched_1.16.4.jar:git-Paper-352]
20.03 12:49:23 [Server] INFO at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[patched_1.16.4.jar:git-Paper-352]
20.03 12:49:23 [Server] INFO at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:65) ~[patched_1.16.4.jar:git-Paper-352]
20.03 12:49:23 [Server] INFO at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:275) ~[patched_1.16.4.jar:git-Paper-352]
20.03 12:49:23 [Server] INFO at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:243) ~[patched_1.16.4.jar:git-Paper-352]
20.03 12:49:23 [Server] INFO at org.yaml.snakeyaml.Yaml.dump(Yaml.java:220) ~[patched_1.16.4.jar:git-Paper-352]
20.03 12:49:23 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:41) ~[patched_1.16.4.jar:git-Paper-352]
20.03 12:49:23 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:65) ~[patched_1.16.4.jar:git-Paper-352]
20.03 12:49:23 [Server] INFO at net.shortninja.staffplus.server.data.file.DataFile.save(DataFile.java:45) ~[?:?]
20.03 12:49:23 [Server] INFO at net.shortninja.staffplus.session.SessionLoader.save(SessionLoader.java:120) ~[?:?]
20.03 12:49:23 [Server] INFO at net.shortninja.staffplus.session.SessionLoader.lambda$saveSession$0(SessionLoader.java:110) ~[?:?]
20.03 12:49:23 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-352]
20.03 12:49:23 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-352]
20.03 12:49:23 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-352]
20.03 12:49:23 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
20.03 12:49:23 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
20.03 12:49:23 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by garagepoort** [comment]
Hey @KayleePhoto 
It seems something went wrong when saving the staff+ data file.
Could you share your data.yml file?

**Comment by garagepoort** [comment]
@KayleePhoto I will release a new version of Staff++ in half an hour.
This will try to make the saving of the data file more stable. When that version is released could you download it and see if that changes anything. Also remove your current data.yml file from the staffplus folder

**Comment by KayleePhoto** [comment]
> @KayleePhoto I will release a new version of Staff++ in half an hour.
> This will try to make the saving of the data file more stable. When that version is released could you download it and see if that changes anything. Also remove your current data.yml file from the staffplus folder

Sorry for the very late reply.
I'll get right onto getting that version

**Comment by KayleePhoto** [comment]
Okay, thank you! It doesn't list an error now.
