### ISSUE TITLE
Could not pass event PlayerJoinEvent to StaffPlus v1.16.67

### ISSUE THREAD

**Issue by davidgb8246** [garagepoort/StaffPlusPlus#161]
Hey, I have this problem so many times, someone help me.

`[19:14:25] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to StaffPlus v1.16.67
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[server.jar:3055-Spigot-4225eac-6f55b5b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:3055-Spigot-4225eac-6f55b5b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[server.jar:3055-Spigot-4225eac-6f55b5b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[server.jar:3055-Spigot-4225eac-6f55b5b]
	at net.minecraft.server.v1_16_R3.PlayerList.a(PlayerList.java:267) ~[server.jar:3055-Spigot-4225eac-6f55b5b]
	at net.minecraft.server.v1_16_R3.LoginListener.c(LoginListener.java:173) ~[server.jar:3055-Spigot-4225eac-6f55b5b]
	at net.minecraft.server.v1_16_R3.LoginListener.tick(LoginListener.java:71) ~[server.jar:3055-Spigot-4225eac-6f55b5b]
	at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:229) ~[server.jar:3055-Spigot-4225eac-6f55b5b]
	at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:143) ~[server.jar:3055-Spigot-4225eac-6f55b5b]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1246) ~[server.jar:3055-Spigot-4225eac-6f55b5b]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:394) ~[server.jar:3055-Spigot-4225eac-6f55b5b]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1127) ~[server.jar:3055-Spigot-4225eac-6f55b5b]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:966) ~[server.jar:3055-Spigot-4225eac-6f55b5b]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[server.jar:3055-Spigot-4225eac-6f55b5b]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.util.NoSuchElementException: packet_handler
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1119) ~[server.jar:3055-Spigot-4225eac-6f55b5b]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:260) ~[server.jar:3055-Spigot-4225eac-6f55b5b]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:249) ~[server.jar:3055-Spigot-4225eac-6f55b5b]
	at com.comphenix.protocol.injector.netty.PipelineProxy.addBefore(PipelineProxy.java:61) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3$1.addBefore(ChannelInjector.java:314) ~[?:?]
	at net.shortninja.staffplus.server.compatibility.v1_1x.Protocol_v1_16_R3.inject(Protocol_v1_16_R3.java:148) ~[?:?]
	at net.shortninja.staffplus.core.domain.player.listeners.PlayerJoin.onJoin(PlayerJoin.java:60) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[server.jar:3055-Spigot-4225eac-6f55b5b]
	... 14 more`

**Comment by garagepoort** [comment]
Hey @davidgb8246 

Could you come onto our discord? It might be easier to communicate that way. https://discord.gg/Nwvubuz

**Comment by garagepoort** [comment]
Closed due to inactivity. Please open a new ticket if this still persists
