### ISSUE TITLE
IPv6 IPs make Errors

### ISSUE THREAD

**Issue by 2020Sanoj** [garagepoort/StaffPlusPlus#175]
[Craft Scheduler Thread - 280 - StaffPlus/WARN]: [StaffPlus] Plugin StaffPlus v1.17.8 generated an exception while executing task 723                                                                                      
net.shortninja.staffplus.core.common.exceptions.DatabaseException: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'ip' at row 1                                                          
        at net.shortninja.staffplus.core.domain.player.ip.database.AbstractSqlPlayerIpRepository.save(AbstractSqlPlayerIpRepository.java:51) ~[?:?]                                                                                   
        at net.shortninja.staffplus.core.domain.player.ip.PlayerIpService.savePlayerIp(PlayerIpService.java:30) ~[?:?]                                                                                                                
        at net.shortninja.staffplus.core.domain.player.ip.UpdateIpListener.lambda$updateIp$0(UpdateIpListener.java:25) ~[?:?]                                                                                                         
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Airplane-23]                                                                                                          
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Airplane-23]                                                                                                 
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Airplane-23]                                                                                 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]                                                                                                                                     
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]                                                                                                                                     
        at java.lang.Thread.run(Thread.java:831) [?:?]                                                                                                                                                                                
Caused by: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'ip' at row 1                                                                                                                  
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104) ~[patched_1.17.1.jar:git-Airplane-23]                                                                                  
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[patched_1.17.1.jar:git-Airplane-23]                                                                                          
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092) ~[patched_1.17.1.jar:git-Airplane-23]                                                                                   
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040) ~[patched_1.17.1.jar:git-Airplane-23]                                                                                   
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347) ~[patched_1.17.1.jar:git-Airplane-23]                                                                                      
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025) ~[patched_1.17.1.jar:git-Airplane-23]                                                                                           
        at net.shortninja.staffplus.libs.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[?:?]                                                                                           
        at net.shortninja.staffplus.libs.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[?:?]                                                                                  
        at net.shortninja.staffplus.core.domain.player.ip.database.AbstractSqlPlayerIpRepository.save(AbstractSqlPlayerIpRepository.java:48) ~[?:?]                                                                                   
        ... 8 more
        

        I think the Plugin says that my IP is too long to save it in the mysql (mariadb) Database (IP: 2003:d3:2f08:ab01:6d72:***:853:587e)

**Comment by garagepoort** [comment]
Hey @2020Sanoj 
You're right, this is a bug. Will fix it in next release.

**Comment by 2020Sanoj** [comment]
Ok
