### ISSUE TITLE
How do i establish a db connection the right way? (config.yml)

### ISSUE THREAD

**Issue by gin-iro** [garagepoort/StaffPlusPlus#197]
this are the standard settings, which work like a charm:

storage:
  type: sqlite
  mysql:
    host: localhost
    user: root
    database: root
    password: mypass
    port: 3306
    max-pool-size: 5
    ssl-enabled: false

first thing: I am 100% sure that i am using the right IP address, as well as user, database, and password.

What is the right way to enter the data? When I restart the server with smth like this: 

storage:
  type: mysql
  mysql:
    host: 123.123.123.123
    user: root
    database: minecraft
    password: password
    port: 3306
    
Things do no longer work.

adding ' does not change anything:

storage:
  type: 'mysql'
  mysql:
    host: '123.123.123.123'
    user: 'root'
    database: 'minecraft'
    password: 'mypass'
    port: 3306

What am I doing wrong?

**Comment by garagepoort** [comment]
Hey @gin-iro 

What happens when you start up with these settings. That should work

**Comment by gin-iro** [comment]
This: [12:39:31] [Server thread/ERROR]: Error occurred while enabling StaffPlus v1.18.8 (Is it up to date?)
net.shortninja.staffplus.core.be.garagepoort.mcioc.IocException: Mc-Ioc bean exceptions: [Cannot instantiate bean with type net.shortninja.staffplus.core.application.database.DatabaseInitializer.]
	at net.shortninja.staffplus.core.be.garagepoort.mcioc.IocContainer.createBean(IocContainer.java:244) ~[staffplusplus-core-1.18.8.jar:?]
	at net.shortninja.staffplus.core.be.garagepoort.mcioc.IocContainer.instantiateBean(IocContainer.java:208) ~[staffplusplus-core-1.18.8.jar:?]
	at net.shortninja.staffplus.core.be.garagepoort.mcioc.IocContainer.loadIocBeans(IocContainer.java:75) ~[staffplusplus-core-1.18.8.jar:?]
	at net.shortninja.staffplus.core.be.garagepoort.mcioc.IocContainer.init(IocContainer.java:46) ~[staffplusplus-core-1.18.8.jar:?]
	at net.shortninja.staffplus.core.be.garagepoort.mcioc.TubingPlugin.onEnable(TubingPlugin.java:27) ~[staffplusplus-core-1.18.8.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) ~[paper-1.18.1.jar:git-Paper-155]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) ~[paper-1.18.1.jar:git-Paper-155]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-155]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-155]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-155]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-155]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-155]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.shortninja.staffplus.core.be.garagepoort.mcioc.IocContainer.createBean(IocContainer.java:239) ~[staffplusplus-core-1.18.8.jar:?]
	... 15 more
Caused by: net.shortninja.staffplus.core.be.garagepoort.mcsqlmigrations.SqlMigrationException: Failure retrieving max migration version: {}
	at net.shortninja.staffplus.core.be.garagepoort.mcsqlmigrations.Migrations.getMaxVersion(Migrations.java:118) ~[staffplusplus-core-1.18.8.jar:?]
	at net.shortninja.staffplus.core.be.garagepoort.mcsqlmigrations.Migrations.runMigrations(Migrations.java:67) ~[staffplusplus-core-1.18.8.jar:?]
	at net.shortninja.staffplus.core.be.garagepoort.mcsqlmigrations.Migrations.run(Migrations.java:29) ~[staffplusplus-core-1.18.8.jar:?]
	at net.shortninja.staffplus.core.application.database.DatabaseInitializer.<init>(DatabaseInitializer.java:20) ~[staffplusplus-core-1.18.8.jar:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.shortninja.staffplus.core.be.garagepoort.mcioc.IocContainer.createBean(IocContainer.java:239) ~[staffplusplus-core-1.18.8.jar:?]
	... 15 more
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'version' in 'field list'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1206) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at net.shortninja.staffplus.libs.com.zaxxer.hikari.pool.ProxyStatement.executeQuery(ProxyStatement.java:111) ~[staffplusplus-core-1.18.8.jar:?]
	at net.shortninja.staffplus.libs.com.zaxxer.hikari.pool.HikariProxyStatement.executeQuery(HikariProxyStatement.java) ~[staffplusplus-core-1.18.8.jar:?]
	at net.shortninja.staffplus.core.be.garagepoort.mcsqlmigrations.Migrations.getMaxVersion(Migrations.java:113) ~[staffplusplus-core-1.18.8.jar:?]
	at net.shortninja.staffplus.core.be.garagepoort.mcsqlmigrations.Migrations.runMigrations(Migrations.java:67) ~[staffplusplus-core-1.18.8.jar:?]
	at net.shortninja.staffplus.core.be.garagepoort.mcsqlmigrations.Migrations.run(Migrations.java:29) ~[staffplusplus-core-1.18.8.jar:?]
	at net.shortninja.staffplus.core.application.database.DatabaseInitializer.<init>(DatabaseInitializer.java:20) ~[staffplusplus-core-1.18.8.jar:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.shortninja.staffplus.core.be.garagepoort.mcioc.IocContainer.createBean(IocContainer.java:239) ~[staffplusplus-core-1.18.8.jar:?]
	... 15 more

**Comment by gin-iro** [comment]
I tried it with ' and without. Yes, I am 100% sure that I used the right db address, username, and password.

**Comment by gin-iro** [comment]
It is used by several other plugins. I tested it on a fresh installation and it worked. So I am assuming that the issue is on our end. I'll come back to you when I know more.

**Comment by redbau** [comment]
> Is this database only used by Staff++ or are there other plugins connected to the same database.
> If other plugins are using it, can you try creating a separate database for staff++

Hi @garagepoort yes gin-iro and I have been working together on this config issue. Yes the db shares tables, so I was hoping for a way to prefix tables for Staff++
1. No startup errors connecting, only when trying to select
2. The tables don't seem to get created
3. Seems odd to get no connection error and no table creation error...

**Comment by garagepoort** [comment]
@redbau 
It seems some other plugin already created a `migrations` table. This is the one that is failing.
normally all staff++ tables are prefixed with `sp_` but this one table is not prefixed.

I won't be able to fix this very soon. If possible I would just suggest to give staff++ a separate database

**Comment by garagepoort** [comment]
New property added in the latest version to bypass this problem:

`migrations-table-name: 'migrations'`
