### ISSUE TITLE
GUI errors when trying to go back in certain out of the box menus.

### ISSUE THREAD

**Issue by Alucardz997** [garagepoort/StaffPlusPlus#203]
Console throwing errors when trying to use the closing GUI item on certain our of the box modules.
Server software is Paper 1.16.5 latest - Staff++ 1.16.102.

In order to reproduce the issue: 
- Have a Dummy Player around and warn him once. (warn details are irrelevant) 
- Start the staffmode via /staff.
- Access the player-details-module in the provided toolbar. (Dummy Player needs to be close)
- Access the warnings history.
- Select one warning to view the details of.
- Take no action on the warning, just go back.
- Attempt to go back one more time - to the player-details-module GUI.
- There it is, complete loss of functionality until GUI resets.

Note: Same happens for multiple parts of the default GUI, this is just an example that I chose to provide as example.

```
[02:13:41] [Server thread/ERROR]: Could not pass event InventoryClickEvent to StaffPlus v1.16.102
net.shortninja.staffplus.core.be.garagepoort.mcioc.IocException: Mc-Ioc bean exceptions: [Unable to execute gui action]
	at net.shortninja.staffplus.core.be.garagepoort.mcioc.gui.GuiActionService.executeAction(GuiActionService.java:107) ~[?:?]
	at net.shortninja.staffplus.core.be.garagepoort.mcioc.gui.InventoryClick.lambda$onClick$0(InventoryClick.java:38) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.shortninja.staffplus.core.be.garagepoort.mcioc.gui.InventoryClick.onClick(InventoryClick.java:28) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor745.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-792]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-792]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-792]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2715) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-792]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at net.shortninja.staffplus.core.be.garagepoort.mcioc.gui.actionquery.ActionQueryParser.getParams(ActionQueryParser.java:61) ~[?:?]
	at net.shortninja.staffplus.core.be.garagepoort.mcioc.gui.GuiActionService.executeAction(GuiActionService.java:87) ~[?:?]
	... 23 more
```

**Comment by garagepoort** [comment]
Hey @Alucardz997 
Fixed in latest release 1.18.12
