### ISSUE TITLE
Warnings system errors

### ISSUE THREAD

**Issue by Ryvix** [garagepoort/StaffPlusPlus#217]
Hello,

I was testing this nice looking plugin out and when I tested warnings I got some errors.

I'm using the sqlite mode.

I'm on Paper MC (paper-1.19.1-94.jar).

<details><summary>View Errors</summary>
<p>

```
[11:20:34] [Craft Scheduler Thread - 17 - StaffPlusPlus/WARN]: [StaffPlusPlus] Plugin StaffPlusPlus v1.19.9 generated an exception while executing task 888
net.shortninja.staffplus.core.be.garagepoort.mcioc.IocException: Mc-Ioc bean exception: [Unable to execute gui action]
        at net.shortninja.staffplus.core.be.garagepoort.mcioc.tubinggui.GuiActionService.lambda$processAsyncGuiAction$5(GuiActionService.java:156) ~[staffplusplus-core-1.19.9.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.1.jar:git-Paper-91]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.1.jar:git-Paper-91]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: net.shortninja.staffplus.core.be.garagepoort.mcsqlmigrations.helpers.DatabaseException: java.sql.SQLException: column 13 out of bounds [1,12]
        at net.shortninja.staffplus.core.be.garagepoort.mcsqlmigrations.helpers.QueryBuilder.find(QueryBuilder.java:117) ~[staffplusplus-core-1.19.9.jar:?]
        at net.shortninja.staffplus.core.be.garagepoort.mcsqlmigrations.helpers.SqliteQueryBuilder.find(SqliteQueryBuilder.java:63) ~[staffplusplus-core-1.19.9.jar:?]
        at net.shortninja.staffplus.core.domain.staff.warn.warnings.database.SqlWarnRepository.getWarnings(SqlWarnRepository.java:97) ~[staffplusplus-core-1.19.9.jar:?]
        at net.shortninja.staffplus.core.domain.staff.warn.warnings.WarnService.getWarnings(WarnService.java:157) ~[staffplusplus-core-1.19.9.jar:?]
        at net.shortninja.staffplus.core.domain.staff.warn.warnings.gui.WarningsGuiController.getWarnings(WarningsGuiController.java:84) ~[staffplusplus-core-1.19.9.jar:?]
        at net.shortninja.staffplus.core.domain.staff.warn.warnings.gui.WarningsGuiController.lambda$warningsOverview$1(WarningsGuiController.java:75) ~[staffplusplus-core-1.19.9.jar:?]
        at net.shortninja.staffplus.core.be.garagepoort.mcioc.tubinggui.GuiActionService.lambda$processAsyncGuiAction$5(GuiActionService.java:150) ~[staffplusplus-core-1.19.9.jar:?]
        ... 6 more
Caused by: java.sql.SQLException: column 13 out of bounds [1,12]
        at org.sqlite.core.CoreResultSet.checkCol(CoreResultSet.java:91) ~[sqlite-jdbc-3.36.0.3.jar:?]
        at org.sqlite.core.CoreResultSet.markCol(CoreResultSet.java:104) ~[sqlite-jdbc-3.36.0.3.jar:?]
        at org.sqlite.jdbc3.JDBC3ResultSet.getInt(JDBC3ResultSet.java:395) ~[sqlite-jdbc-3.36.0.3.jar:?]
        at net.shortninja.staffplus.core.domain.staff.warn.warnings.database.SqlWarnRepository.buildWarning(SqlWarnRepository.java:232) ~[staffplusplus-core-1.19.9.jar:?]
        at net.shortninja.staffplus.core.be.garagepoort.mcsqlmigrations.helpers.QueryBuilder.find(QueryBuilder.java:112) ~[staffplusplus-core-1.19.9.jar:?]
        at net.shortninja.staffplus.core.be.garagepoort.mcsqlmigrations.helpers.SqliteQueryBuilder.find(SqliteQueryBuilder.java:63) ~[staffplusplus-core-1.19.9.jar:?]
        at net.shortninja.staffplus.core.domain.staff.warn.warnings.database.SqlWarnRepository.getWarnings(SqlWarnRepository.java:97) ~[staffplusplus-core-1.19.9.jar:?]
        at net.shortninja.staffplus.core.domain.staff.warn.warnings.WarnService.getWarnings(WarnService.java:157) ~[staffplusplus-core-1.19.9.jar:?]
        at net.shortninja.staffplus.core.domain.staff.warn.warnings.gui.WarningsGuiController.getWarnings(WarningsGuiController.java:84) ~[staffplusplus-core-1.19.9.jar:?]
        at net.shortninja.staffplus.core.domain.staff.warn.warnings.gui.WarningsGuiController.lambda$warningsOverview$1(WarningsGuiController.java:75) ~[staffplusplus-core-1.19.9.jar:?]
        at net.shortninja.staffplus.core.be.garagepoort.mcioc.tubinggui.GuiActionService.lambda$processAsyncGuiAction$5(GuiActionService.java:150) ~[staffplusplus-core-1.19.9.jar:?]
        ... 6 more
```
```
[12:40:54 WARN]: [StaffPlusPlus] Plugin StaffPlusPlus v1.19.9 generated an exception while executing task 118
java.lang.NoSuchMethodError: 'void net.minecraft.network.protocol.game.ClientboundSystemChatPacket.<init>(net.minecraft.network.chat.IChatBaseComponent, int)'
        at net.shortninja.staffplus.server.compatibility.v1_1x.JsonSender_v1_19_R0.createTextPacket(JsonSender_v1_19_R0.java:34) ~[staffplusplus-core-1.19.9.jar:?]
        at net.shortninja.staffplus.server.compatibility.v1_1x.JsonSender_v1_19_R0.send(JsonSender_v1_19_R0.java:14) ~[staffplusplus-core-1.19.9.jar:?]
        at net.shortninja.staffplus.core.common.JsonSenderService.send(JsonSenderService.java:21) ~[staffplusplus-core-1.19.9.jar:?]
        at net.shortninja.staffplus.core.domain.staff.warn.warnings.WarningNotifierListener.sendMessage(WarningNotifierListener.java:70) ~[staffplusplus-core-1.19.9.jar:?]
        at net.shortninja.staffplus.core.domain.staff.warn.warnings.WarningNotifierListener.lambda$notifyWarnings$1(WarningNotifierListener.java:56) ~[staffplusplus-core-1.19.9.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.1.jar:git-Paper-91]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.1.jar:git-Paper-91]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

</p>
</details>

The first one is after I issue a warning to a player and try to view it. For the first error I notice I can run the query to get warnings directly in an sqlite browser and it appears to join properly even though there are no appeals yet and it seems to show the 13th column there from the appeals table join but maybe doesn't do that properly on the server for some reason. Maybe the sqlite library doesn't properly do the join? I dunno.

The second error is when the player logs in after having a warning and getting the notice about it I think. I don't really know for sure but I think that might be what it is. Maybe the second error is related more to do with the new chat features in 1.19.1 rather than specifically the warnings?

I may have some other issues and whatnot such as it saying to nag the author about using System.out/err.print. Says to use the plugin logger instead.

And another thing that says `[13:09:43 WARN]: [StaffPlusPlus] Loaded class kotlin.Unit from LandsDiscordBot v2.5.1 which is not a depend or softdepend of this plugin.` I'm not sure what that is about or if it's at all related. I do have a DiscordSRV plugin which integrates with the Lands Discord plugin. I haven't setup the Discord features of Staff++ yet but hopefully can get to that at some point.

Anyway, thank you very much for working on this plugin! I look forward to using it and hope to help any way I can in the future (code, donations, reports, etc).

**Comment by garagepoort** [comment]
Hey @Ryvix 

Thank you for the detailed bug report.
I have confirmed both of them and will release a new version today to fix it

**Comment by Ryvix** [comment]
I tested making a new warning, and typing /my-warnings and appealing it and then approving the appeal and it worked.

However, after that when I go to delete it says i nchat Warning with id[1] not found.

In the log it gives me another error.

<details><summary>View Error</summary>
<p>

```
! [Mon 13:47:07 WARN  StaffPlusPlus] Plugin StaffPlusPlus v1.19.10 generated an exception while executing task 15690
net.shortninja.staffplus.core.be.garagepoort.mcioc.IocException: Mc-Ioc bean exception: [Unable to execute gui action]
    at staffplusplus-core-1.19.10.jar//net.shortninja.staffplus.core.be.garagepoort.mcioc.tubinggui.GuiActionService.lambda$processAsyncGuiAction$5(GuiActionService.java:156)
    at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
    at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: net.shortninja.staffplus.core.common.exceptions.BusinessException: Warning with id [1] not found
    at staffplusplus-core-1.19.10.jar//net.shortninja.staffplus.core.domain.staff.warn.warnings.WarnService.lambda$getWarning$0(WarnService.java:112)
    at java.base/java.util.Optional.orElseThrow(Optional.java:403)
    at staffplusplus-core-1.19.10.jar//net.shortninja.staffplus.core.domain.staff.warn.warnings.WarnService.getWarning(WarnService.java:112)
    at staffplusplus-core-1.19.10.jar//net.shortninja.staffplus.core.domain.staff.warn.warnings.gui.WarningsGuiController.lambda$warningDetail$6(WarningsGuiController.java:111)
    at staffplusplus-core-1.19.10.jar//net.shortninja.staffplus.core.be.garagepoort.mcioc.tubinggui.GuiActionService.lambda$processAsyncGuiAction$5(GuiActionService.java:150)
    ... 6 more
```

</p>
</details>

I'm not sure if it's possibly somehow related to my previous testing since I think I deleted it manually before by restoring the player file on the server.

Thank you!

**Comment by garagepoort** [comment]
hey @Ryvix 
This was indeed another bug. Should be solved with the latest release.

**Comment by Ryvix** [comment]
This seems to work great now. Thank you!
