### ISSUE TITLE
/my-warnings error with MySQL storage

### ISSUE THREAD

**Issue by BetoCR16** [garagepoort/StaffPlusPlus#218]
Using storage with MySQL and execute the command `/my-warnings`, the GUI doesn't shows up and this error appers in console:
- StaffPlusPlus version 1.19.13
``` 
[23:26:34 WARN]: [StaffPlusPlus] Plugin StaffPlusPlus v1.19.13 generated an exception while executing task 34
net.shortninja.staffplus.core.be.garagepoort.mcioc.IocException: Mc-Ioc bean exception: [Unable to execute gui action]
        at net.shortninja.staffplus.core.be.garagepoort.mcioc.tubinggui.GuiActionService.lambda$processAsyncGuiAction$5(GuiActionService.java:155) ~[staffplusplus-core-1.19.13.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-131]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-131]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: net.shortninja.staffplus.core.be.garagepoort.mcsqlmigrations.helpers.DatabaseException: java.sql.SQLIntegrityConstraintViolationException: Column 'timestamp' in order clause is ambiguous
        at net.shortninja.staffplus.core.be.garagepoort.mcsqlmigrations.helpers.QueryBuilder.find(QueryBuilder.java:117) ~[staffplusplus-core-1.19.13.jar:?]
        at net.shortninja.staffplus.core.domain.staff.warn.warnings.database.SqlWarnRepository.getWarnings(SqlWarnRepository.java:97) ~[staffplusplus-core-1.19.13.jar:?]
        at net.shortninja.staffplus.core.domain.staff.warn.warnings.WarnService.getWarnings(WarnService.java:157) ~[staffplusplus-core-1.19.13.jar:?]
        at net.shortninja.staffplus.core.domain.staff.warn.warnings.gui.WarningsGuiController.lambda$myWarningsOverview$2(WarningsGuiController.java:89) ~[staffplusplus-core-1.19.13.jar:?]
        at net.shortninja.staffplus.core.be.garagepoort.mcioc.tubinggui.GuiActionService.lambda$processAsyncGuiAction$5(GuiActionService.java:149) ~[staffplusplus-core-1.19.13.jar:?]
        ... 6 more
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'timestamp' in order clause is ambiguous
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117) ~[mysql-connector-java-8.0.29.jar:8.0.29]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.29.jar:8.0.29]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916) ~[mysql-connector-java-8.0.29.jar:8.0.29]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972) ~[mysql-connector-java-8.0.29.jar:8.0.29]
        at net.shortninja.staffplus.libs.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[staffplusplus-core-1.19.13.jar:?]
        at net.shortninja.staffplus.libs.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[staffplusplus-core-1.19.13.jar:?]
        at net.shortninja.staffplus.core.be.garagepoort.mcsqlmigrations.helpers.QueryBuilder.find(QueryBuilder.java:110) ~[staffplusplus-core-1.19.13.jar:?]
        at net.shortninja.staffplus.core.domain.staff.warn.warnings.database.SqlWarnRepository.getWarnings(SqlWarnRepository.java:97) ~[staffplusplus-core-1.19.13.jar:?]
        at net.shortninja.staffplus.core.domain.staff.warn.warnings.WarnService.getWarnings(WarnService.java:157) ~[staffplusplus-core-1.19.13.jar:?]
        at net.shortninja.staffplus.core.domain.staff.warn.warnings.gui.WarningsGuiController.lambda$myWarningsOverview$2(WarningsGuiController.java:89) ~[staffplusplus-core-1.19.13.jar:?]
        at net.shortninja.staffplus.core.be.garagepoort.mcioc.tubinggui.GuiActionService.lambda$processAsyncGuiAction$5(GuiActionService.java:149) ~[staffplusplus-core-1.19.13.jar:?]
        ... 6 more
```

**Comment by garagepoort** [comment]
@BetoCR16 
Thank you for reporting. Has been fixed in the latest release which can be found on https://staffplusplus.org
