### ISSUE TITLE
Issue on first installation (1.19.2)

### ISSUE THREAD

**Issue by FaMa91** [garagepoort/StaffPlusPlus#220]
Issue on first installation (1.19.2)

[10:54:54] [Server thread/INFO]: [StaffPlusPlus] Enabling StaffPlusPlus v1.19.14
[10:54:54] [Server thread/INFO]: [StaffPlusPlus] First installation detected
[10:54:54] [Server thread/WARN]: java.io.IOException: No such file or directory
[10:54:54] [Server thread/WARN]:    at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
[10:54:54] [Server thread/WARN]:    at java.base/java.io.File.createNewFile(File.java:1043)
[10:54:54] [Server thread/WARN]:    at staffplusplus-core-1.19.14.jar//net.shortninja.staffplus.core.StaffPlusPlus.beforeEnable(StaffPlusPlus.java:43)
[10:54:54] [Server thread/WARN]:    at staffplusplus-core-1.19.14.jar//net.shortninja.staffplus.core.be.garagepoort.mcioc.tubingbukkit.TubingBukkitPlugin.onEnable(TubingBukkitPlugin.java:24)
[10:54:54] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[10:54:54] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[10:54:54] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[10:54:54] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565)
[10:54:54] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479)
[10:54:54] [Server thread/WARN]:    at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
[10:54:54] [Server thread/WARN]:    at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422)
[10:54:54] [Server thread/WARN]:    at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
[10:54:54] [Server thread/WARN]:    at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1126)
[10:54:54] [Server thread/WARN]:    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[10:54:54] [Server thread/WARN]:    at java.base/java.lang.Thread.run(Thread.java:833)
[10:54:56] [Server thread/INFO]: [StaffPlusPlus] Using SQLITE storage
[10:54:56] [Server thread/INFO]: [StaffPlusPlus] No custom staff mode modules to load
[10:54:56] [Server thread/ERROR]: [StaffPlusPlus] [STDERR] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[10:54:56] [Server thread/WARN]: Nag author(s): '[Shortninja,Qball,Garagepoort]' of 'StaffPlusPlus' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[10:54:56] [Server thread/ERROR]: [StaffPlusPlus] [STDERR] SLF4J: Defaulting to no-operation (NOP) logger implementation
[10:54:56] [Server thread/ERROR]: [StaffPlusPlus] [STDERR] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

**Comment by garagepoort** [comment]
Duplicate

**Comment by FaMa91** [comment]
I can't find the same issue. Duplicate of which One?

**Comment by garagepoort** [comment]
Sorry @FaMa91 I misread it. 
This indeed is not a duplicate.
