### ISSUE TITLE
Could not pass event VanishOffEvent to StaffPlusPlus v1.19.18

### ISSUE THREAD

**Issue by Ryvix** [garagepoort/StaffPlusPlus#225]
Hello,

I just updated to MC 1.9.3 and updated all the plugins including this one. I get this error when exiting staff mode.

I'm running the latest Paper build 338.

Thank you!

```
- [Fri 11:42:41 ERROR Minecraft] Could not pass event VanishOffEvent to StaffPlusPlus v1.19.18
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_19_R2.entity.CraftPlayer cannot be cast to class net.minecraft.server.level.EntityPlayer (org.bukkit.craftbukkit.v1_19_R2.entity.CraftPlayer and net.minecraft.server.level.EntityPlayer are in unnamed module of loader java.net.URLClassLoader @25f38edc)
    at staffplusplus-core-1.19.18.jar//net.shortninja.staffplus.server.compatibility.v1_1x.Protocol_v1_19_R2.listVanish(Protocol_v1_19_R2.java:91)
    at staffplusplus-core-1.19.18.jar//net.shortninja.staffplus.core.domain.staff.vanish.TotalVanishStrategy.listVanish(TotalVanishStrategy.java:62)
    at staffplusplus-core-1.19.18.jar//net.shortninja.staffplus.core.domain.staff.vanish.TotalVanishStrategy.unvanish(TotalVanishStrategy.java:68)
    at staffplusplus-core-1.19.18.jar//net.shortninja.staffplus.core.domain.staff.vanish.gui.VanishPlayersBukkitService.lambda$onUnvanish$1(VanishPlayersBukkitService.java:43)
    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
    at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
    at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
    at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
    at staffplusplus-core-1.19.18.jar//net.shortninja.staffplus.core.domain.staff.vanish.gui.VanishPlayersBukkitService.lambda$onUnvanish$2(VanishPlayersBukkitService.j
```

**Comment by garagepoort** [comment]
@Ryvix Should be fixed in latest release 1.19.19
