### ISSUE TITLE
Error on startup with 1.20 version

### ISSUE THREAD

**Issue by nicholasrobertm** [garagepoort/StaffPlusPlus#231]
Hey there!

Not sure if it's actually impacting anything but this error is thrown on the console in 1.20.2. I also tested the 1.20.1 version and it throws a similar error.

```[21:35:53 ERROR] [Minecraft]: Error occurred while enabling StaffPlusPlus v1.20.2 (Is it up to date?)
net.shortninja.staffplus.core.be.garagepoort.mcioc.libs.io.github.classgraph.ClassGraphException: Uncaught exception during scan
        at net.shortninja.staffplus.core.be.garagepoort.mcioc.libs.io.github.classgraph.ClassGraph.scan(ClassGraph.java:1606) ~[?:?]
        at net.shortninja.staffplus.core.be.garagepoort.mcioc.libs.io.github.classgraph.ClassGraph.scan(ClassGraph.java:1623) ~[?:?]
        at net.shortninja.staffplus.core.be.garagepoort.mcioc.libs.io.github.classgraph.ClassGraph.scan(ClassGraph.java:1636) ~[?:?]
        at net.shortninja.staffplus.core.be.garagepoort.mcioc.IocContainer.init(IocContainer.java:47) ~[?:?]
        at net.shortninja.staffplus.core.be.garagepoort.mcioc.TubingPlugin.initIocContainer(TubingPlugin.java:23) ~[?:?]
        at net.shortninja.staffplus.core.be.garagepoort.mcioc.tubingbukkit.TubingBukkitPlugin.onEnable(TubingBukkitPlugin.java:25) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:266) ~[arclight-1.20.1-1.0.4-SNAPSHOT-2606ff93.jar%23177!/:arclight-1.20.1-1.0.4-SNAPSHOT-2606ff93]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight-1.20.1-1.0.4-SNAPSHOT-2606ff93.jar%23177!/:arclight-1.20.1-1.0.4-SNAPSHOT-2606ff93]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[arclight-1.20.1-1.0.4-SNAPSHOT-2606ff93.jar%23177!/:arclight-1.20.1-1.0.4-SNAPSHOT-2606ff93]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServerMixin.java:546) ~[arclight-1.20.1-1.0.4-SNAPSHOT-2606ff93.jar%23177!/:arclight-1.20.1-1.0.4-SNAPSHOT-2606ff93]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServerMixin.java:460) ~[arclight-1.20.1-1.0.4-SNAPSHOT-2606ff93.jar%23177!/:arclight-1.20.1-1.0.4-SNAPSHOT-2606ff93]
        at net.minecraft.server.MinecraftServer.handler$zba000$arclight$enablePlugins(MinecraftServerMixin.java:2137) ~[server-1.20.1-20230612.114412-srg.jar%23193!/:?]
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServerMixin.java:385) ~[server-1.20.1-20230612.114412-srg.jar%23193!/:?]
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServerMixin.java:308) ~[server-1.20.1-20230612.114412-srg.jar%23193!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:164) ~[server-1.20.1-20230612.114412-srg.jar%23193!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2028) ~[server-1.20.1-20230612.114412-srg.jar%23193!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23193!/:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Could not call moduleReader.list()
        at net.shortninja.staffplus.core.be.garagepoort.mcioc.libs.io.github.classgraph.ModuleReaderProxy.list(ModuleReaderProxy.java:110) ~[?:?]
        at net.shortninja.staffplus.core.be.garagepoort.mcioc.libs.io.github.classgraph.ClasspathElementModule.scanPaths(ClasspathElementModule.java:304) ~[?:?]
        at net.shortninja.staffplus.core.be.garagepoort.mcioc.libs.io.github.classgraph.Scanner$4.processWorkUnit(Scanner.java:1091) ~[?:?]
        at net.shortninja.staffplus.core.be.garagepoort.mcioc.libs.io.github.classgraph.Scanner$4.processWorkUnit(Scanner.java:1085) ~[?:?]
        at net.shortninja.staffplus.core.be.garagepoort.mcioc.libs.nonapi.io.github.classgraph.concurrency.WorkQueue.runWorkLoop(WorkQueue.java:246) ~[?:?]
        at net.shortninja.staffplus.core.be.garagepoort.mcioc.libs.nonapi.io.github.classgraph.concurrency.WorkQueue.runWorkQueue(WorkQueue.java:161) ~[?:?]
        at net.shortninja.staffplus.core.be.garagepoort.mcioc.libs.io.github.classgraph.Scanner.processWorkUnits(Scanner.java:314) ~[?:?]
        at net.shortninja.staffplus.core.be.garagepoort.mcioc.libs.io.github.classgraph.Scanner.openClasspathElementsThenScan(Scanner.java:1083) ~[?:?]
        at net.shortninja.staffplus.core.be.garagepoort.mcioc.libs.io.github.classgraph.Scanner.call(Scanner.java:1142) ~[?:?]
        at net.shortninja.staffplus.core.be.garagepoort.mcioc.libs.io.github.classgraph.Scanner.call(Scanner.java:81) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        ... 1 more```

**Comment by Nch0001** [comment]
```
[02:32:36] [Server thread/INFO]: [StaffPlusPlus] Enabling StaffPlusPlus v1.20.5
[02:32:37] [DiscordSRV - Initialization/INFO]: [DiscordSRV] [JDA] Login Successful!
[02:32:37] [pool-68-thread-1/INFO]: [DiscordSRV] DiscordSRV is up-to-date. (6405e850eea61a4b9bf4f0d0cbb80fe20b3cfb90)
[02:32:37] [Server thread/ERROR]: Error occurred while enabling StaffPlusPlus v1.20.5 (Is it up to date?)
net.shortninja.staffplus.core.be.garagepoort.mcioc.IocException: Mc-Ioc bean exception: [Cannot instantiate bean with type net.shortninja.staffplus.core.be.garagepoort.mcioc.configuration.ConfigurationLoader.]
	at net.shortninja.staffplus.core.be.garagepoort.mcioc.IocContainer.createBean(IocContainer.java:241) ~[staffplusplus-core-1.20.5.jar:?]
	at net.shortninja.staffplus.core.be.garagepoort.mcioc.IocContainer.instantiateBean(IocContainer.java:203) ~[staffplusplus-core-1.20.5.jar:?]
	at net.shortninja.staffplus.core.be.garagepoort.mcioc.IocContainer.loadIocBeans(IocContainer.java:92) ~[staffplusplus-core-1.20.5.jar:?]
	at net.shortninja.staffplus.core.be.garagepoort.mcioc.IocContainer.init(IocContainer.java:54) ~[staffplusplus-core-1.20.5.jar:?]
	at net.shortninja.staffplus.core.be.garagepoort.mcioc.TubingPlugin.initIocContainer(TubingPlugin.java:23) ~[staffplusplus-core-1.20.5.jar:?]
	at net.shortninja.staffplus.core.be.garagepoort.mcioc.tubingbukkit.TubingBukkitPlugin.onEnable(TubingBukkitPlugin.java:25) ~[staffplusplus-core-1.20.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-496]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-496]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-496]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.shortninja.staffplus.core.be.garagepoort.mcioc.IocContainer.createBean(IocContainer.java:235) ~[staffplusplus-core-1.20.5.jar:?]
	... 17 more
Caused by: java.lang.NullPointerException: Cannot invoke "net.shortninja.staffplus.core.be.garagepoort.mcioc.configuration.yaml.configuration.file.FileConfiguration.contains(String)" because "langConfig" is null
	at net.shortninja.staffplus.core.application.config.migrators.StaffChatMessageFormatMigrator.migrate(StaffChatMessageFormatMigrator.java:17) ~[staffplusplus-core-1.20.5.jar:?]
	at net.shortninja.staffplus.core.be.garagepoort.mcioc.configuration.files.AutoUpdater.lambda$runMigrations$2(AutoUpdater.java:67) ~[staffplusplus-core-1.20.5.jar:?]
	at java.util.Arrays$ArrayList.forEach(Arrays.java:4204) ~[?:?]
	at net.shortninja.staffplus.core.be.garagepoort.mcioc.configuration.files.AutoUpdater.runMigrations(AutoUpdater.java:67) ~[staffplusplus-core-1.20.5.jar:?]
	at net.shortninja.staffplus.core.be.garagepoort.mcioc.configuration.ConfigurationLoader.loadConfig(ConfigurationLoader.java:55) ~[staffplusplus-core-1.20.5.jar:?]
	at net.shortninja.staffplus.core.be.garagepoort.mcioc.configuration.ConfigurationLoader.<init>(ConfigurationLoader.java:36) ~[staffplusplus-core-1.20.5.jar:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.shortninja.staffplus.core.be.garagepoort.mcioc.IocContainer.createBean(IocContainer.java:235) ~[staffplusplus-core-1.20.5.jar:?]
	... 17 more
[02:32:37] [Server thread/INFO]: [StaffPlusPlus] Disabling StaffPlusPlus v1.20.5
[02:32:37] [Server thread/INFO]: [StaffPlusPlus] Staff++ is now disabling!
[02:32:37] [Server thread/INFO]: [StaffPlusPlus] Staff++ disabled!
```
same issue 1.20.4 I had a working version then updated it and it stopped working even upon downgrading
